"""
venue_economics_data.py
========================
Synthetic data generator for venue-level ad-revenue economics, built on top
of the venues already generated by data_generation.py (venues.csv is read
as-is, unmodified).

Business scenario
------------------
The causal/MMM pipeline elsewhere in this project answers the *advertiser*
side (did the campaign work, how should spend be allocated). This part
answers Atmosphere's *own* revenue question: given a venue's observable
characteristics, what weekly ad revenue should it realize — and where is
the network leaving money on the table?

Two synthetic, LATENT (not given to the revenue model) mechanisms are
injected on top of each venue's observable characteristics, exactly so the
model's out-of-sample recovery of them can be validated before trusting the
model's flags conceptually — same ground-truth-first pattern used
throughout this project:

1. `true_ad_revenue_potential` — what a venue COULD earn given its traffic,
   inventory (screens), engagement (dwell time), audience quality, and its
   local market's advertiser demand (`geo_demand_multiplier`, latent per
   geo_cluster). Also modestly scaled by the RCT-calibrated per-exposure
   lift for that venue_type — a venue_type advertising works better on is
   hypothesized to command a modest demand/pricing premium.
2. `monetization_efficiency` — the SHARE of that potential actually
   realized, driven by (a) a small number of "thin sales coverage" geo
   markets where the whole market underperforms its potential, and (b) an
   independent ~15% of venues with venue-level execution gaps (stale
   pricing, low fill rate, low advertiser awareness). Neither is given to
   the model — they are exactly what `realized_ad_revenue - predicted`
   should recover.

`realized_ad_revenue = true_ad_revenue_potential * monetization_efficiency *
(1 + noise)` is the only revenue figure the model is trained on — the same
figure Atmosphere's own books would show. `true_ad_revenue_potential` and
`monetization_efficiency` are written to venue_economics_ground_truth.json
purely for out-of-sample validation of the model in venue_revenue_model.py.

NOTE: BASE_WEEKLY_AD_RATE below is an illustrative demo rate card, not a
researched real Atmosphere/DOOH figure — same honest-scope caveat as the
budget allocator's cost-per-frequency-unit assumption.
"""

import json
import os

import numpy as np
import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
OUT_TABLES = os.path.join(BASE_DIR, "outputs", "tables")

RNG_SEED = 20260903  # independent stream from data_generation.py
rng = np.random.default_rng(RNG_SEED)

N_GEO_CLUSTERS = 20  # must match data_generation.py
N_THIN_COVERAGE_GEOS = 3
N_EXPANSION_GEOS = 5   # brand-new markets, prospects only, no existing venues
N_PROSPECTS_PER_TYPE = 20

BASE_WEEKLY_AD_RATE = {
    # illustrative $ weekly ad-revenue potential for an "average" venue of
    # this type, before traffic/inventory/quality/demand scaling
    "restaurant": 380.0,
    "gym": 300.0,
    "bar": 420.0,
    "waiting_room": 150.0,
}

REVENUE_NOISE_SD_FRAC = 0.07


def _load_mmm_calibrated_lift():
    """The validated per-exposure value from the causal/MMM pipeline, one
    number per venue_type — the feature that carries that causal work into
    the revenue model as input, not as a re-derivation. Falls back to a
    flat 1.0 (no adjustment) if the MMM hasn't been run yet, so this script
    never hard-depends on run order beyond data_generation.py."""
    path = os.path.join(OUT_TABLES, "mmm_params.csv")
    if not os.path.exists(path):
        return {}
    mmm = pd.read_csv(path)
    return dict(zip(mmm["venue_type"], mmm["beta_calibrated"]))


def _geo_demand_multipliers(geo_ids):
    """One latent demand-strength draw per geo_cluster id (log-normal,
    mean 1.0) — proxy for local advertiser demand density. Same draw is
    reused for existing and expansion-market geo ids so the two pools are
    on a comparable footing."""
    draws = rng.lognormal(mean=0.0, sigma=0.22, size=len(geo_ids))
    return dict(zip(geo_ids, draws))


def build_venue_economics(venues, calibrated_lift):
    v = venues.copy()

    vtype_mean_baseline = v.groupby("venue_type")["baseline_level"].transform("mean")
    vtype_mean_dwell = v.groupby("venue_type")["dwell_time_min"].transform("mean")

    existing_geo_ids = sorted(v["geo_cluster"].unique().tolist())
    thin_coverage_geos = sorted(
        rng.choice(existing_geo_ids, size=N_THIN_COVERAGE_GEOS, replace=False).tolist()
    )
    expansion_geo_ids = list(range(N_GEO_CLUSTERS, N_GEO_CLUSTERS + N_EXPANSION_GEOS))
    geo_demand = _geo_demand_multipliers(existing_geo_ids + expansion_geo_ids)

    if calibrated_lift:
        lift_vals = np.array(list(calibrated_lift.values()))
        lift_lo, lift_hi = lift_vals.min(), lift_vals.max()
        lift_norm = {
            k: (val - lift_lo) / max(lift_hi - lift_lo, 1e-9) for k, val in calibrated_lift.items()
        }
    else:
        lift_norm = {}

    def lift_factor(vtype):
        # modest +/-15% swing around 1.0 — a real but secondary driver, not
        # the dominant one (traffic/quality/geo dominate) — see README notes
        # on this being an honest, imperfect predictor rather than a proxy
        # that trivially reconstructs revenue from the calibrated lift number.
        return 0.85 + 0.30 * lift_norm.get(vtype, 0.5)

    v["geo_demand_multiplier"] = v["geo_cluster"].map(geo_demand)
    v["true_ad_revenue_potential"] = (
        v["venue_type"].map(BASE_WEEKLY_AD_RATE)
        * (v["baseline_level"] / vtype_mean_baseline)
        * (0.6 + 0.4 * v["screen_count"] / 3.0)
        * (0.7 + 0.3 * v["dwell_time_min"] / vtype_mean_dwell)
        * (0.5 + v["audience_quality"])
        * v["geo_demand_multiplier"]
        * v["venue_type"].map(lift_factor)
    )

    # --- latent monetization efficiency (never given to the model) ---
    base_eff = np.clip(rng.normal(0.85, 0.08, size=len(v)), 0.40, 1.05)
    thin_coverage_mask = v["geo_cluster"].isin(thin_coverage_geos)
    geo_gap_multiplier = np.where(thin_coverage_mask, 0.65, 1.0)
    individual_gap_mask = rng.random(len(v)) < 0.15
    individual_gap_multiplier = np.where(
        individual_gap_mask, rng.uniform(0.55, 0.80, size=len(v)), 1.0
    )
    v["monetization_efficiency"] = np.clip(
        base_eff * geo_gap_multiplier * individual_gap_multiplier, 0.20, 1.05
    )
    v["thin_coverage_market"] = thin_coverage_mask
    v["individual_execution_gap"] = individual_gap_mask

    noise = rng.normal(0, REVENUE_NOISE_SD_FRAC, size=len(v))
    v["realized_ad_revenue"] = np.maximum(
        0.0, v["true_ad_revenue_potential"] * v["monetization_efficiency"] * (1 + noise)
    )
    v["calibrated_lift_feature"] = v["venue_type"].map(calibrated_lift) if calibrated_lift else np.nan

    return v, thin_coverage_geos, expansion_geo_ids, geo_demand


def build_prospects(venues, calibrated_lift, expansion_geo_ids, geo_demand):
    """Hypothetical venues NOT yet in the network — the kind of
    characteristics a leasing/scouting team could observe pre-signature
    (type, estimated foot traffic, feasible screen count, dwell-time
    estimate, an audience-quality survey score) but with no revenue history
    yet. Half sit in existing markets (new locations of known market
    strength), half in brand-new "expansion" markets not currently served."""
    venue_types = sorted(venues["venue_type"].unique())
    existing_geo_ids = sorted(venues["geo_cluster"].unique().tolist())
    rows = []
    prospect_id = 0
    for vtype in venue_types:
        vsub = venues[venues["venue_type"] == vtype]
        bp_mean, bp_sd = vsub["baseline_level"].mean(), vsub["baseline_level"].std()
        dwell_mean, dwell_sd = vsub["dwell_time_min"].mean(), vsub["dwell_time_min"].std()
        for i in range(N_PROSPECTS_PER_TYPE):
            in_expansion_market = i < N_PROSPECTS_PER_TYPE // 2
            geo_cluster = (
                int(rng.choice(expansion_geo_ids)) if in_expansion_market
                else int(rng.choice(existing_geo_ids))
            )
            baseline_level = max(30.0, rng.normal(bp_mean, bp_sd))
            dwell_time_min = max(5.0, rng.normal(dwell_mean, dwell_sd))
            screen_count = int(rng.integers(1, 4))
            audience_quality = float(np.clip(rng.normal(0.6, 0.15), 0.1, 0.95))
            rows.append(dict(
                prospect_id=f"P{prospect_id:04d}",
                venue_type=vtype,
                geo_cluster=geo_cluster,
                in_expansion_market=in_expansion_market,
                baseline_level=baseline_level,
                dwell_time_min=dwell_time_min,
                screen_count=screen_count,
                audience_quality=audience_quality,
                calibrated_lift_feature=calibrated_lift.get(vtype, np.nan),
            ))
            prospect_id += 1

    prospects = pd.DataFrame(rows)
    # true potential kept ONLY for a held-out sanity check on ranking quality —
    # not used anywhere in the model input.
    vtype_mean_baseline = venues.groupby("venue_type")["baseline_level"].mean()
    vtype_mean_dwell = venues.groupby("venue_type")["dwell_time_min"].mean()
    if calibrated_lift:
        lift_vals = np.array(list(calibrated_lift.values()))
        lift_lo, lift_hi = lift_vals.min(), lift_vals.max()
    else:
        lift_lo, lift_hi = 0.0, 1.0

    def lift_factor(vtype):
        norm = (calibrated_lift.get(vtype, (lift_lo + lift_hi) / 2) - lift_lo) / max(lift_hi - lift_lo, 1e-9)
        return 0.85 + 0.30 * norm

    prospects["geo_demand_multiplier"] = prospects["geo_cluster"].map(geo_demand)
    prospects["true_ad_revenue_potential_prospect"] = (
        prospects["venue_type"].map(BASE_WEEKLY_AD_RATE)
        * (prospects["baseline_level"] / prospects["venue_type"].map(vtype_mean_baseline))
        * (0.6 + 0.4 * prospects["screen_count"] / 3.0)
        * (0.7 + 0.3 * prospects["dwell_time_min"] / prospects["venue_type"].map(vtype_mean_dwell))
        * (0.5 + prospects["audience_quality"])
        * prospects["geo_demand_multiplier"]
        * prospects["venue_type"].apply(lift_factor)
    )
    return prospects


def main():
    venues = pd.read_csv(os.path.join(DATA_DIR, "venues.csv"))
    calibrated_lift = _load_mmm_calibrated_lift()

    econ, thin_coverage_geos, expansion_geo_ids, geo_demand = build_venue_economics(venues, calibrated_lift)
    prospects = build_prospects(venues, calibrated_lift, expansion_geo_ids, geo_demand)

    econ.to_csv(os.path.join(DATA_DIR, "venue_economics.csv"), index=False)
    prospects.to_csv(os.path.join(DATA_DIR, "prospect_venues.csv"), index=False)

    venue_economics_ground_truth = {
        "rng_seed": RNG_SEED,
        "thin_coverage_geos": thin_coverage_geos,
        "expansion_geo_ids": expansion_geo_ids,
        "base_weekly_ad_rate": BASE_WEEKLY_AD_RATE,
        "note": (
            "true_ad_revenue_potential and monetization_efficiency (incl. "
            "thin_coverage_market / individual_execution_gap flags) are latent "
            "ground truth for validating venue_revenue_model.py's out-of-sample "
            "recovery only -- the model itself is never given these columns."
        ),
    }
    with open(os.path.join(DATA_DIR, "venue_economics_ground_truth.json"), "w") as f:
        json.dump(venue_economics_ground_truth, f, indent=2)

    print(f"venue_economics: {econ.shape}")
    print(f"prospects: {prospects.shape}")
    print(f"thin coverage geos (latent, held out from model): {thin_coverage_geos}")
    print(f"expansion geo ids (prospect-only markets): {expansion_geo_ids}")
    print("\nrealized_ad_revenue by venue_type (mean):")
    print(econ.groupby("venue_type")["realized_ad_revenue"].mean().round(1))
    print(f"\nindividual execution gap venues: {econ['individual_execution_gap'].sum()} / {len(econ)}")
    print(f"thin-coverage-market venues: {econ['thin_coverage_market'].sum()} / {len(econ)}")


if __name__ == "__main__":
    main()
