"""
venue_retention_data.py
========================
Synthetic data generator for venue-level retention/churn risk, built on top
of the venues already generated by data_generation.py and the revenue
economics from venue_economics_data.py (both read as-is, unmodified).

Business scenario
------------------
venue_revenue_model.py answers "what makes a venue valuable" (its realized
and potential ad revenue). This part answers the other half of the JD's own
framing -- "what puts a venue at risk": which existing venues are likely to
leave the network, and which day-to-day operational signals (engagement,
complaints, screen uptime, competitor outreach) are the leading indicators
sales/ops should act on, not just correlates to note.

Two synthetic, LATENT (not given to the churn model) mechanisms are
injected on top of each venue's observable characteristics, exactly so the
model's out-of-sample recovery of them can be validated before trusting its
flags conceptually -- same ground-truth-first pattern used throughout this
project:

1. `competitive_pressure_market` -- a handful of geo_clusters where a rival
   place-based network is aggressively courting venues, elevating churn
   hazard market-wide (the churn-side analogue of `thin_coverage_market` on
   the revenue side).
2. `relationship_execution_gap` -- an independent ~15% of venues with a
   poor account-management relationship (slow issue resolution, stale
   contact), elevating that venue's own hazard regardless of market (the
   churn-side analogue of `individual_execution_gap`).

On top of those, a venue_type baseline hazard (bars/restaurants -- higher
hospitality-sector turnover -- run hotter than gyms/waiting rooms) and a
tenure-shaped hazard (elevated in the first 6 months, and again near likely
annual contract-renewal windows) combine into `true_churn_risk_90d`, a
latent propensity. `churned_next_quarter` (the only outcome the model is
trained on) is a Bernoulli draw from that propensity -- the same
"latent-mechanism -> noisy realized outcome" pattern as
`realized_ad_revenue` on the revenue side.

The model never sees `true_churn_risk_90d`, `competitive_pressure_market`,
or `relationship_execution_gap` -- only the noisy, ops-observable signals
below, generated as imperfect proxies of the latent risk:
engagement_trend_90d, screen_uptime_pct, complaint_count_90d,
self_ad_promo_utilization, competitor_outreach_flag, tenure_months, plus
`realized_ad_revenue` from the economics side. That last one is deliberately
NOT engineered to be a near-zero-importance sanity check this time: it ends
up carrying real permutation importance in venue_retention_model.py, because
venue_type drives both a venue's base ad-revenue rate AND its baseline churn
hazard (hospitality types run hotter on both), so revenue and risk share a
confound rather than one causing the other -- a good example of the kind of
correlation-vs-causation caveat worth flagging before anyone acts on it.
"""

import json
import os

import numpy as np
import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")

RNG_SEED = 20260904  # independent stream from data_generation.py / venue_economics_data.py
rng = np.random.default_rng(RNG_SEED)

N_COMPETITIVE_GEOS = 3

# venue_type baseline hazard (90-day churn probability at "average" risk) --
# hospitality (restaurants/bars) has materially higher underlying business
# turnover than gyms/waiting rooms (illustrative demo rates, not researched
# real DOOH churn benchmarks -- same honest-scope caveat as elsewhere).
BASE_HAZARD = {
    "restaurant": 0.10,
    "gym": 0.05,
    "bar": 0.12,
    "waiting_room": 0.04,
}


def _logit(p):
    return np.log(p / (1 - p))


def _sigmoid(x):
    return 1 / (1 + np.exp(-x))


def build_retention_data(venues, econ):
    v = venues[["venue_id", "venue_type", "geo_cluster", "traffic_tier"]].merge(
        econ[["venue_id", "realized_ad_revenue"]], on="venue_id", how="left"
    )
    n = len(v)

    existing_geo_ids = sorted(v["geo_cluster"].unique().tolist())
    competitive_geos = sorted(
        rng.choice(existing_geo_ids, size=N_COMPETITIVE_GEOS, replace=False).tolist()
    )
    competitive_mask = v["geo_cluster"].isin(competitive_geos)

    relationship_gap_mask = rng.random(n) < 0.15

    # tenure: how long each venue has been in the network -- a real,
    # observable field, but its relationship to churn hazard (below) is a
    # latent, nonlinear shape the model has to learn from data.
    tenure_months = rng.integers(1, 49, size=n).astype(float)  # up to 4 years

    # --- latent true churn propensity (never given to the model) ---
    base_logit = np.log(np.array([BASE_HAZARD[t] / (1 - BASE_HAZARD[t]) for t in v["venue_type"]]))
    competitive_bump = np.where(competitive_mask, 0.9, 0.0)
    relationship_bump = np.where(relationship_gap_mask, 1.1, 0.0)
    # early-tenure honeymoon-period risk + a bump near annual renewal windows
    early_tenure_bump = np.where(tenure_months <= 6, 0.5, 0.0)
    months_to_renewal = tenure_months % 12
    renewal_window_bump = np.where((months_to_renewal <= 1) | (months_to_renewal >= 11), 0.6, 0.0)
    noise_logit = rng.normal(0, 0.35, size=n)

    true_logit = base_logit + competitive_bump + relationship_bump + early_tenure_bump + renewal_window_bump + noise_logit
    true_churn_risk_90d = np.clip(_sigmoid(true_logit), 0.01, 0.95)
    churned_next_quarter = rng.random(n) < true_churn_risk_90d

    # --- observable, noisy proxies of the latent risk (what the model gets) ---
    risk_z = _logit(true_churn_risk_90d)  # smooth continuous driver for proxies
    engagement_trend_90d = -6.0 * (risk_z - np.median(risk_z)) + rng.normal(0, 4.0, size=n)  # % change, negative = declining
    screen_uptime_pct = np.clip(96.0 - 10.0 * relationship_gap_mask - 4.0 * (risk_z - np.median(risk_z)) + rng.normal(0, 3.0, size=n), 40.0, 100.0)
    complaint_count_90d = np.clip(
        rng.poisson(lam=np.clip(0.6 + 2.2 * _sigmoid(risk_z), 0.1, None)), 0, None
    )
    self_ad_promo_utilization = np.clip(70.0 - 25.0 * _sigmoid(risk_z) + rng.normal(0, 8.0, size=n), 0.0, 100.0)
    competitor_outreach_flag = rng.random(n) < np.where(competitive_mask, 0.55, 0.12)

    v["tenure_months"] = tenure_months
    v["engagement_trend_90d"] = engagement_trend_90d
    v["screen_uptime_pct"] = screen_uptime_pct
    v["complaint_count_90d"] = complaint_count_90d
    v["self_ad_promo_utilization"] = self_ad_promo_utilization
    v["competitor_outreach_flag"] = competitor_outreach_flag
    v["churned_next_quarter"] = churned_next_quarter
    v["true_churn_risk_90d"] = true_churn_risk_90d
    v["competitive_pressure_market"] = competitive_mask
    v["relationship_execution_gap"] = relationship_gap_mask

    return v, competitive_geos


def main():
    venues = pd.read_csv(os.path.join(DATA_DIR, "venues.csv"))
    econ = pd.read_csv(os.path.join(DATA_DIR, "venue_economics.csv"))

    retention, competitive_geos = build_retention_data(venues, econ)
    retention.to_csv(os.path.join(DATA_DIR, "venue_retention.csv"), index=False)

    ground_truth = {
        "rng_seed": RNG_SEED,
        "competitive_pressure_geos": competitive_geos,
        "base_hazard_by_venue_type": BASE_HAZARD,
        "note": (
            "true_churn_risk_90d (incl. competitive_pressure_market / "
            "relationship_execution_gap flags) is latent ground truth for "
            "validating venue_retention_model.py's out-of-sample recovery "
            "only -- the model itself is never given these columns, only "
            "churned_next_quarter and the observable engagement/ops signals."
        ),
    }
    with open(os.path.join(DATA_DIR, "venue_retention_ground_truth.json"), "w") as f:
        json.dump(ground_truth, f, indent=2)

    print(f"venue_retention: {retention.shape}")
    print(f"competitive-pressure geos (latent, held out from model): {competitive_geos}")
    print(f"churned_next_quarter rate: {retention['churned_next_quarter'].mean():.3f}")
    print("\nchurn rate by venue_type:")
    print(retention.groupby("venue_type")["churned_next_quarter"].mean().round(3))
    print(f"\nrelationship execution gap venues: {retention['relationship_execution_gap'].sum()} / {len(retention)}")


if __name__ == "__main__":
    main()
